/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.City;
import model.CityDirectory;
import model.Community;
import model.CommunityDirectory;
import model.DoctorDirectory;
import model.EncounterHistory;
import model.HospitalDirectory;
import model.House;
import model.HouseDirectory;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author mahith
 */



public class CommunityAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunityAdminPanel
     */
    
    HouseDirectory houseDirectory;
    CommunityDirectory communityDirectory;
    CityDirectory cityDirectory;
    PersonDirectory personDirectory;
    PatientDirectory patientDirectory;
    DoctorDirectory doctorDirectory;
    EncounterHistory encounterHistory;
    HospitalDirectory hospitalDirectory;
    JSplitPane splitPane;
    Person person;
    
    City selectedCity;
    Community selectedCommunity;
    House selectedHouse;
   
    
    
    public CommunityAdminPanel(Person person,PersonDirectory personDirectory, PatientDirectory patientDirectory, DoctorDirectory doctorDirectory,EncounterHistory encounterHistory,HospitalDirectory hospitalDirectory,HouseDirectory houseDirectory, CommunityDirectory communityDirectory, CityDirectory cityDirectory, JSplitPane splitPane) {
        initComponents();
        
        this.houseDirectory = houseDirectory;
        this.communityDirectory = communityDirectory;
        this.cityDirectory = cityDirectory;
        this.personDirectory = personDirectory;
        this.patientDirectory = patientDirectory;
        this.doctorDirectory = doctorDirectory;
        this.encounterHistory = encounterHistory;
        this.hospitalDirectory= hospitalDirectory;
        this.person = person;
        this.splitPane = splitPane;
        
        populateCities();
        populateCommunities();
        populateHouses();
        
        cityPanel.setVisible(false);
        communityPanel.setVisible(false);
        housePanel.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCommunities = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHouses = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCities = new javax.swing.JTable();
        btnCreateCity = new javax.swing.JButton();
        btnCreateCommunity = new javax.swing.JButton();
        btnHouse = new javax.swing.JButton();
        btnUpdateCity = new javax.swing.JButton();
        btnUpdateCommunity = new javax.swing.JButton();
        btnUpdateHouse = new javax.swing.JButton();
        btnDeleteCity = new javax.swing.JButton();
        btnDeleteCommunity = new javax.swing.JButton();
        btnDeleteHouse = new javax.swing.JButton();
        cityPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNewCity = new javax.swing.JTextField();
        btnSaveCity = new javax.swing.JButton();
        communityPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNewCommunity = new javax.swing.JTextField();
        btnSaveCommunity = new javax.swing.JButton();
        chComCity = new javax.swing.JComboBox<>();
        housePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNewHouse = new javax.swing.JTextField();
        chCommunity = new javax.swing.JComboBox<>();
        chHouseCity = new javax.swing.JComboBox<>();
        btnSaveHouse = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCommunities.setBackground(new java.awt.Color(255, 255, 204));
        tblCommunities.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Community"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCommunities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCommunitiesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCommunities);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 37, 249, 170));

        tblHouses.setBackground(new java.awt.Color(255, 255, 204));
        tblHouses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Houses"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHouses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHousesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHouses);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 37, 250, 170));

        tblCities.setBackground(new java.awt.Color(255, 255, 204));
        tblCities.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCitiesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblCities);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 37, 237, 170));

        btnCreateCity.setText("Create City");
        btnCreateCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCityActionPerformed(evt);
            }
        });
        add(btnCreateCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 225, -1, -1));

        btnCreateCommunity.setText("Create Community");
        btnCreateCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCommunityActionPerformed(evt);
            }
        });
        add(btnCreateCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 225, -1, -1));

        btnHouse.setText("Create House");
        btnHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHouseActionPerformed(evt);
            }
        });
        add(btnHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 225, -1, -1));

        btnUpdateCity.setText("Update City");
        btnUpdateCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCityActionPerformed(evt);
            }
        });
        add(btnUpdateCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 266, -1, -1));

        btnUpdateCommunity.setText("Update Community");
        btnUpdateCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCommunityActionPerformed(evt);
            }
        });
        add(btnUpdateCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 266, -1, -1));

        btnUpdateHouse.setText("Update House");
        btnUpdateHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateHouseActionPerformed(evt);
            }
        });
        add(btnUpdateHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 266, -1, -1));

        btnDeleteCity.setText("Delete");
        btnDeleteCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCityActionPerformed(evt);
            }
        });
        add(btnDeleteCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 225, -1, -1));

        btnDeleteCommunity.setText("Delete");
        btnDeleteCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCommunityActionPerformed(evt);
            }
        });
        add(btnDeleteCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 225, -1, -1));

        btnDeleteHouse.setText("Delete");
        btnDeleteHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHouseActionPerformed(evt);
            }
        });
        add(btnDeleteHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 225, -1, -1));

        cityPanel.setBackground(new java.awt.Color(255, 255, 204));
        cityPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("City");
        cityPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 44, -1, -1));
        cityPanel.add(txtNewCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 44, 112, -1));

        btnSaveCity.setText("Create");
        btnSaveCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCityActionPerformed(evt);
            }
        });
        cityPanel.add(btnSaveCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 117, -1, 21));

        add(cityPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 307, 240, 287));

        communityPanel.setBackground(new java.awt.Color(255, 255, 204));
        communityPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("City");
        communityPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 46, -1, -1));

        jLabel3.setText("Community");
        communityPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 84, -1, -1));
        communityPanel.add(txtNewCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 81, 112, -1));

        btnSaveCommunity.setText("Create");
        btnSaveCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCommunityActionPerformed(evt);
            }
        });
        communityPanel.add(btnSaveCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 152, -1, -1));

        chComCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select..." }));
        communityPanel.add(chComCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 40, 112, -1));

        add(communityPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 307, 265, 287));

        housePanel.setBackground(new java.awt.Color(255, 255, 204));
        housePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("City");
        housePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 45, -1, -1));

        jLabel5.setText("Community");
        housePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 83, -1, -1));

        jLabel6.setText("House");
        housePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 130, -1, -1));
        housePanel.add(txtNewHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 127, 117, -1));

        chCommunity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select..." }));
        housePanel.add(chCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 80, 117, -1));

        chHouseCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select..." }));
        chHouseCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chHouseCityActionPerformed(evt);
            }
        });
        housePanel.add(chHouseCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 39, 117, -1));

        btnSaveHouse.setText("Create");
        btnSaveHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveHouseActionPerformed(evt);
            }
        });
        housePanel.add(btnSaveHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        add(housePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 307, 250, 290));

        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("                   Welcome Community Admin");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 670, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCityActionPerformed
        // TODO add your handling code here:
        txtNewCity.setText("");
        cityPanel.setVisible(true);
        
    }//GEN-LAST:event_btnCreateCityActionPerformed

    private void btnCreateCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCommunityActionPerformed
        // TODO add your handling code here:
        communityPanel.setVisible(true);
        
        btnSaveCity.setText("Create");
                chComCity.setSelectedIndex(0);
                txtNewCommunity.setText("");    
        try{
            chComCity.removeAllItems();
                chComCity.addItem("Select...");
        }catch(Exception e){
            
        }
                
                
                for(City city:cityDirectory.getCityDirectory()){
                    chComCity.addItem(city.getCity());
                }
    }//GEN-LAST:event_btnCreateCommunityActionPerformed

    private void btnHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHouseActionPerformed
        // TODO add your handling code here:
        housePanel.setVisible(true);
        btnSaveHouse.setText("Create");
        try{
            chHouseCity.removeAllItems();
            chHouseCity.addItem("Select...");
            chCommunity.addItem("Select...");
                
                
        }catch(Exception e){
            
        }
                
        for(City city:cityDirectory.getCityDirectory()){
            chHouseCity.addItem(city.getCity()); 
        }
        
    }//GEN-LAST:event_btnHouseActionPerformed

    private void chHouseCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chHouseCityActionPerformed
        // TODO add your handling code here:
        
        String houseCity= chHouseCity.getSelectedItem().toString();
        
            chCommunity.removeAllItems();
            chCommunity.addItem("Select...");
            chHouseCity.addItem("Select...");
        for(Community community:communityDirectory.getCommunityDirectory()){
            if(community.getCity() == houseCity){
                chCommunity.addItem(community.getCommunity());
            }
                    
                }
    }//GEN-LAST:event_chHouseCityActionPerformed

    private void btnSaveCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCityActionPerformed
        // TODO add your handling code here:
        if(btnSaveCity.getText().equals("Create")){
            City newCity = cityDirectory.addCity();
        
            newCity.setCity(txtNewCity.getText());

            JOptionPane.showMessageDialog(this, "City Created");
            populateCities();
            cityPanel.setVisible(false);
        }else{
           
            
            City upCity = cityDirectory.getCity(selectedCity.getCity());
            upCity.setCity(txtNewCity.getText());
            JOptionPane.showMessageDialog(this, "City Updated");
            populateCities();
            cityPanel.setVisible(false);
            btnSaveCity.setText("Create");
            
        }
        txtNewCity.setText("");
    }//GEN-LAST:event_btnSaveCityActionPerformed

    private void btnSaveCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCommunityActionPerformed
        // TODO add your handling code here:
        
        if(btnSaveCommunity.getText().equals("Create")){
            Community newCommunity = communityDirectory.addCommunity();
        
            newCommunity.setCommunity(txtNewCommunity.getText());
            newCommunity.setCity(chComCity.getSelectedItem().toString());
            
            JOptionPane.showMessageDialog(this, "Community Created");
            populateCommunities();
            communityPanel.setVisible(false);
            
        }else{
            Community newCommunity = communityDirectory.getCommunity(selectedCommunity.getCommunity());
            
            newCommunity.setCommunity(txtNewCommunity.getText());
            newCommunity.setCity(chComCity.getSelectedItem().toString());
            
            JOptionPane.showMessageDialog(this, "Community Updated");
            populateCommunities();
            communityPanel.setVisible(false);
            btnSaveCommunity.setText("Create");
        }
        
        
  
    }//GEN-LAST:event_btnSaveCommunityActionPerformed

    private void btnSaveHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveHouseActionPerformed
        // TODO add your handling code here:
        if(btnSaveHouse.getText().equals("Create")){
            House newHouse = houseDirectory.addHouse();
        
            newHouse.setCommunity(chCommunity.getSelectedItem().toString());
            newHouse.setCity(chHouseCity.getSelectedItem().toString());
            newHouse.setHouse(txtNewHouse.getText());
            
            JOptionPane.showMessageDialog(this, "House Created");
            populateHouses();
            
            housePanel.setVisible(false);
        }else{
            House newHouse = houseDirectory.getHouse(selectedHouse.getHouse());
        
            newHouse.setCommunity(chCommunity.getSelectedItem().toString());
            newHouse.setCity(chHouseCity.getSelectedItem().toString());
            newHouse.setHouse(txtNewHouse.getText());
            
            JOptionPane.showMessageDialog(this, "House Updated");
            populateHouses();
            
            housePanel.setVisible(false);
            btnSaveHouse.setText("Create");
        }
        chHouseCity.setSelectedIndex(0);
        chCommunity.setSelectedIndex(0);
        txtNewHouse.setText("");
        
    }//GEN-LAST:event_btnSaveHouseActionPerformed

    private void tblCitiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCitiesMouseClicked
        // TODO add your handling code here:
        
        
        int index = tblCities.getSelectedRow();
        TableModel model = tblCities.getModel();
        
        String cityName = model.getValueAt(index, 0).toString();
        selectedCity = cityDirectory.getCity(cityName);
        
        
    }//GEN-LAST:event_tblCitiesMouseClicked

    private void tblCommunitiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCommunitiesMouseClicked
        // TODO add your handling code here:
        int index = tblCommunities.getSelectedRow();
        TableModel model = tblCommunities.getModel();
        
        String communityName = model.getValueAt(index, 0).toString();
        selectedCommunity = communityDirectory.getCommunity(communityName);
    }//GEN-LAST:event_tblCommunitiesMouseClicked

    private void tblHousesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHousesMouseClicked
        // TODO add your handling code here:
        int index = tblHouses.getSelectedRow();
        TableModel model = tblHouses.getModel();
        
        String houseName = model.getValueAt(index, 0).toString();
        selectedHouse = houseDirectory.getHouse(houseName);
        
    }//GEN-LAST:event_tblHousesMouseClicked

    private void btnDeleteCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCityActionPerformed
        // TODO add your handling code here:
        if(selectedCity!=null){
            cityDirectory.deleteCity(selectedCity);
            
            JOptionPane.showMessageDialog(this, "City Deleted");
            populateCities();
        }else{
            JOptionPane.showMessageDialog(this, "Select a City to Delete");
        }
    }//GEN-LAST:event_btnDeleteCityActionPerformed

    private void btnDeleteCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCommunityActionPerformed
        // TODO add your handling code here:
        if(selectedCommunity!=null){
            communityDirectory.deleteCommunity(selectedCommunity);
            
            JOptionPane.showMessageDialog(this, "Community Deleted");
            populateCommunities();
        }else{
            JOptionPane.showMessageDialog(this, "Select a Community to Delete");
        }
    }//GEN-LAST:event_btnDeleteCommunityActionPerformed

    private void btnDeleteHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHouseActionPerformed
        // TODO add your handling code here:
        if(selectedHouse!=null){
            houseDirectory.deleteHouse(selectedHouse);
            
            JOptionPane.showMessageDialog(this, "House Deleted");
            populateHouses();
        }else{
            JOptionPane.showMessageDialog(this, "Select a House to Delete");
        }
    }//GEN-LAST:event_btnDeleteHouseActionPerformed

    private void btnUpdateCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCityActionPerformed
        // TODO add your handling code here:
        if(selectedCity!=null){
            cityPanel.setVisible(true);
        
            txtNewCity.setText(selectedCity.getCity());
            btnSaveCity.setText("Update");
            
        }else{
            JOptionPane.showMessageDialog(this, "Select a City to Update");
        }
        
    }//GEN-LAST:event_btnUpdateCityActionPerformed

    private void btnUpdateCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCommunityActionPerformed
        // TODO add your handling code here:
        if(selectedCommunity!=null){
            communityPanel.setVisible(true);
            btnSaveCommunity.setText("Update");
            try{
                chComCity.removeAllItems();
                chComCity.addItem("Select...");
            }catch(Exception e){
                
            }
            
                
                for(City city:cityDirectory.getCityDirectory()){
                    chComCity.addItem(city.getCity());
                }
            
            
        
            chComCity.setSelectedItem(selectedCommunity.getCity());
            txtNewCommunity.setText(selectedCommunity.getCommunity());
            
            
        }else{
            JOptionPane.showMessageDialog(this, "Select a City to Update");
        }
        
        
    }//GEN-LAST:event_btnUpdateCommunityActionPerformed

    private void btnUpdateHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateHouseActionPerformed
        // TODO add your handling code here:
        if(selectedHouse!=null){
            housePanel.setVisible(true);
            btnSaveHouse.setText("Update");
            try{
                chHouseCity.removeAllItems();
            chHouseCity.addItem("Select...");
            chCommunity.addItem("Select...");
            }catch(Exception e){
                
            }
            
                for(City city:cityDirectory.getCityDirectory()){
                    chHouseCity.addItem(city.getCity());
                }

            chHouseCity.setSelectedItem(selectedHouse.getCity());
            chCommunity.setSelectedItem(selectedHouse.getCommunity());
            txtNewHouse.setText(selectedHouse.getHouse());
        }else{
            JOptionPane.showMessageDialog(this, "Please select a House to update/view");
        }
        
        
        
    }//GEN-LAST:event_btnUpdateHouseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        LoginJPanel login = new LoginJPanel(personDirectory,patientDirectory,doctorDirectory,encounterHistory,hospitalDirectory,houseDirectory, communityDirectory,cityDirectory,splitPane);
        splitPane.setRightComponent(login);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCity;
    private javax.swing.JButton btnCreateCommunity;
    private javax.swing.JButton btnDeleteCity;
    private javax.swing.JButton btnDeleteCommunity;
    private javax.swing.JButton btnDeleteHouse;
    private javax.swing.JButton btnHouse;
    private javax.swing.JButton btnSaveCity;
    private javax.swing.JButton btnSaveCommunity;
    private javax.swing.JButton btnSaveHouse;
    private javax.swing.JButton btnUpdateCity;
    private javax.swing.JButton btnUpdateCommunity;
    private javax.swing.JButton btnUpdateHouse;
    private javax.swing.JComboBox<String> chComCity;
    private javax.swing.JComboBox<String> chCommunity;
    private javax.swing.JComboBox<String> chHouseCity;
    private javax.swing.JPanel cityPanel;
    private javax.swing.JPanel communityPanel;
    private javax.swing.JPanel housePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblCities;
    private javax.swing.JTable tblCommunities;
    private javax.swing.JTable tblHouses;
    private javax.swing.JTextField txtNewCity;
    private javax.swing.JTextField txtNewCommunity;
    private javax.swing.JTextField txtNewHouse;
    // End of variables declaration//GEN-END:variables


    public void populateCities(){
        DefaultTableModel model = (DefaultTableModel) tblCities.getModel();
        model.setRowCount(0);
        
        for(City city: cityDirectory.getCityDirectory()){
            
            Object[] Row =new Object[1];
            Row[0] = city.getCity();
            
            model.addRow(Row);
        }
    }
    
    public void populateCommunities(){
        DefaultTableModel model = (DefaultTableModel) tblCommunities.getModel();
        model.setRowCount(0);
        
        for(Community community: communityDirectory.getCommunityDirectory()){
            
            Object[] Row =new Object[1];
            Row[0] = community.getCommunity();
            
            model.addRow(Row);
        }
    }
    
    public void populateHouses(){
        DefaultTableModel model = (DefaultTableModel) tblHouses.getModel();
        model.setRowCount(0);
        
        for(House house: houseDirectory.getHouseDirectory()){
            
            Object[] Row =new Object[1];
            Row[0] = house.getHouse();
            
            model.addRow(Row);
        }
    }

}
