/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.util.Date;
import model.Doctor;
import model.DoctorDirectory;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author mahith
 */
public class HomeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeJFrame
     */
    
    PersonDirectory personDirectory;
    PatientDirectory patientDirectory;
    DoctorDirectory doctorDirectory;
    public HomeJFrame() {
        initComponents();
        
        personDirectory = new PersonDirectory();
        patientDirectory = new PatientDirectory();
        doctorDirectory = new DoctorDirectory();
        
        preDefinedData();
        LoginJPanel login = new LoginJPanel(personDirectory,patientDirectory,doctorDirectory,splitJPane);
        splitJPane.setRightComponent(login);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitJPane = new javax.swing.JSplitPane();
        upperJPanel = new javax.swing.JPanel();
        lowerJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HealthCare System");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        splitJPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        upperJPanel.setPreferredSize(new java.awt.Dimension(800, 75));

        javax.swing.GroupLayout upperJPanelLayout = new javax.swing.GroupLayout(upperJPanel);
        upperJPanel.setLayout(upperJPanelLayout);
        upperJPanelLayout.setHorizontalGroup(
            upperJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        upperJPanelLayout.setVerticalGroup(
            upperJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        splitJPane.setTopComponent(upperJPanel);

        lowerJPanel.setPreferredSize(new java.awt.Dimension(800, 725));

        javax.swing.GroupLayout lowerJPanelLayout = new javax.swing.GroupLayout(lowerJPanel);
        lowerJPanel.setLayout(lowerJPanelLayout);
        lowerJPanelLayout.setHorizontalGroup(
            lowerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        lowerJPanelLayout.setVerticalGroup(
            lowerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );

        splitJPane.setRightComponent(lowerJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitJPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitJPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel lowerJPanel;
    private javax.swing.JSplitPane splitJPane;
    private javax.swing.JPanel upperJPanel;
    // End of variables declaration//GEN-END:variables

    public void preDefinedData(){
        Person person = personDirectory.addPerson();
        Patient patient = patientDirectory.addPatient();
        Doctor doctor = doctorDirectory.addDoctor();
        
        patient.setFirstName("Shubham");
        patient.setLastName("sapkal");
        patient.setAge(25);
        patient.setDateOfBirth(new Date(01-01-2000));
        patient.setEmailAddress("ss@gmail.com");
        patient.setHeight(100);
        patient.setWeight(100);
        patient.setMobileNum("(999)999-9999");
        patient.setUserID("shubham@patient");
        patient.setPassword("password");
        patient.setRole("Patient");
        
        doctor.setFirstName("Aditya");
        doctor.setLastName("Kanala");
        doctor.setDateOfBirth(new Date(2000-20-12));
        doctor.setHospital("Brigham Hospital");
        doctor.setRole("Doctor");
        doctor.setMobileNum("(857)666-666");
        doctor.setUserID("Aditya");
        doctor.setEmailAddress("ak@gmail.com");
        doctor.setPassword("password");
        doctor.setSpecialization("Psychologist");
        
        person.setFirstName("Aditya");
        person.setLastName("Kanala");
        person.setDateOfBirth(new Date(2000-20-12));
        person.setRole("Doctor");
        person.setMobileNum("(857)666-666");
        person.setUserID("aditya@doctor");
        person.setEmailAddress("ak@gmail.com");
        person.setPassword("password");
        
        person.setFirstName("Shubham");
        person.setLastName("sapkal");
        person.setDateOfBirth(new Date(01-01-2000));
        person.setEmailAddress("ss@gmail.com");
        person.setMobileNum("(999)999-9999");
        person.setUserID("shubham@patient");
        person.setUserID("shubham@patient");
        person.setPassword("password");
        person.setRole("Patient");
    } 

}
