/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.CityDirectory;
import model.CommunityDirectory;
import model.Doctor;
import model.DoctorDirectory;
import model.Encounter;
import model.EncounterHistory;
import model.HospitalDirectory;
import model.HouseDirectory;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author mahith
 */
public class PatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientJPanel
     */
    PatientDirectory patientDirectory;
    PersonDirectory personDirectory;
    DoctorDirectory doctorDirectory;
    HospitalDirectory hospitalDirectory;
    
    HouseDirectory houseDirectory;
    CommunityDirectory communityDirectory;
    CityDirectory cityDirectory;
    
    JSplitPane splitPane;
    Person patient;
    EncounterHistory encounterHistory;
    String doctorFname;
    
    public PatientJPanel(Person person, PersonDirectory personDirectory, PatientDirectory patientDirectory, DoctorDirectory doctorDirectory, EncounterHistory encounterHistory,HospitalDirectory hospitalDirectory,HouseDirectory houseDirectory,CommunityDirectory communityDirectory, CityDirectory cityDirectory, JSplitPane splitPane) {
        this.patientDirectory = patientDirectory;
        this.personDirectory = personDirectory;
        this.doctorDirectory = doctorDirectory;
        this.encounterHistory = encounterHistory;
        this.communityDirectory = communityDirectory;
        this.cityDirectory = cityDirectory;
        this.houseDirectory = houseDirectory;
        this.hospitalDirectory = hospitalDirectory;
        this.splitPane = splitPane;
        this.patient = person;
        
        initComponents();
        lblPatient.setText("Welcome "+patient.getFirstName());
        vitalsPanel.setVisible(false);
        bookAppointmentPanel.setVisible(false);
        btnBookAppointment.setVisible(false);
        //scrollEncounters.setVisible(false);
        //chDate.setDateFormatString("MM-dd-YYYY");
        populateDoctorTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        lblPatient = new javax.swing.JLabel();
        lblPersonalDetails = new javax.swing.JLabel();
        txtSearchDoctor = new javax.swing.JTextField();
        btnSearchDoctor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoctors = new javax.swing.JTable();
        scrollEncounters = new javax.swing.JScrollPane();
        tblEncounters = new javax.swing.JTable();
        btnBookAppointment = new javax.swing.JButton();
        vitalsPanel = new javax.swing.JPanel();
        lblBP = new javax.swing.JLabel();
        txtSystole = new javax.swing.JTextField();
        lblSystole = new javax.swing.JLabel();
        lblDiastole = new javax.swing.JLabel();
        txtDiastole = new javax.swing.JTextField();
        lblDiabetes = new javax.swing.JLabel();
        lblPreDiet = new javax.swing.JLabel();
        txtPreDiet = new javax.swing.JTextField();
        lblPostDiet = new javax.swing.JLabel();
        txtPostDiet = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtComments = new javax.swing.JTextArea();
        lblComments = new javax.swing.JLabel();
        lblHeartRate = new javax.swing.JLabel();
        txtHeartRate = new javax.swing.JTextField();
        bookAppointmentPanel = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        chDate = new com.toedter.calendar.JDateChooser();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();
        lblInfo = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPatient.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        lblPatient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 23, 800, -1));

        lblPersonalDetails.setText("   View/Update Details");
        lblPersonalDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPersonalDetailsMouseClicked(evt);
            }
        });
        add(lblPersonalDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 73, 142, -1));
        add(txtSearchDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 70, 140, -1));

        btnSearchDoctor.setText("Search Doctor");
        btnSearchDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDoctorActionPerformed(evt);
            }
        });
        add(btnSearchDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 70, -1, -1));

        tblDoctors.setBackground(new java.awt.Color(255, 255, 204));
        tblDoctors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor", "Hospital", "Community"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDoctors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDoctorsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDoctors);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, 800, 150));

        tblEncounters.setBackground(new java.awt.Color(255, 255, 204));
        tblEncounters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Encounters"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEncounters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEncountersMouseClicked(evt);
            }
        });
        scrollEncounters.setViewportView(tblEncounters);

        add(scrollEncounters, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 261, 236, -1));

        btnBookAppointment.setText("Book Appointment");
        btnBookAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookAppointmentActionPerformed(evt);
            }
        });
        add(btnBookAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 261, 165, -1));

        vitalsPanel.setBackground(new java.awt.Color(204, 204, 255));
        vitalsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBP.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblBP.setText("BP:");
        vitalsPanel.add(lblBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, 58, -1));

        txtSystole.setEditable(false);
        vitalsPanel.add(txtSystole, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 89, 88, -1));

        lblSystole.setText("Systole");
        vitalsPanel.add(lblSystole, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 101, -1, -1));

        lblDiastole.setText("Diastole");
        vitalsPanel.add(lblDiastole, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 92, -1, -1));

        txtDiastole.setEditable(false);
        vitalsPanel.add(txtDiastole, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 89, 88, -1));

        lblDiabetes.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblDiabetes.setText("Diabetes:");
        vitalsPanel.add(lblDiabetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 130, -1, -1));

        lblPreDiet.setText("Pre Diet");
        vitalsPanel.add(lblPreDiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 165, -1, -1));

        txtPreDiet.setEditable(false);
        vitalsPanel.add(txtPreDiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 147, 88, -1));

        lblPostDiet.setText("Post Diet");
        vitalsPanel.add(lblPostDiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 150, -1, -1));

        txtPostDiet.setEditable(false);
        vitalsPanel.add(txtPostDiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 147, 82, -1));

        txtComments.setEditable(false);
        txtComments.setColumns(20);
        txtComments.setRows(5);
        jScrollPane3.setViewportView(txtComments);

        vitalsPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 245, 235, 66));

        lblComments.setText("Comments");
        vitalsPanel.add(lblComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 245, -1, -1));

        lblHeartRate.setText("Heart Rate");
        vitalsPanel.add(lblHeartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 200, -1, -1));

        txtHeartRate.setEditable(false);
        vitalsPanel.add(txtHeartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 188, 88, -1));

        add(vitalsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 314, 320, 374));

        bookAppointmentPanel.setBackground(new java.awt.Color(204, 204, 255));
        bookAppointmentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDate.setText("Date");
        bookAppointmentPanel.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 67, 56, -1));
        bookAppointmentPanel.add(chDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 67, 131, -1));

        txtInfo.setColumns(20);
        txtInfo.setRows(5);
        jScrollPane4.setViewportView(txtInfo);

        bookAppointmentPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 108, 131, -1));

        lblInfo.setText("Info");
        bookAppointmentPanel.add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 118, 42, -1));

        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        bookAppointmentPanel.add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 225, -1, -1));

        add(bookAppointmentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 314, 230, 374));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 29, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void lblPersonalDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPersonalDetailsMouseClicked
        // TODO add your handling code here:
        UpdatePanel update = new UpdatePanel(patient,personDirectory,patientDirectory,doctorDirectory,encounterHistory,hospitalDirectory,houseDirectory,communityDirectory,cityDirectory, splitPane);
        splitPane.setRightComponent(update);
    }//GEN-LAST:event_lblPersonalDetailsMouseClicked

    private void btnBookAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookAppointmentActionPerformed
        // TODO add your handling code here:
        vitalsPanel.setVisible(false);
        bookAppointmentPanel.setVisible(true);
        
    }//GEN-LAST:event_btnBookAppointmentActionPerformed

    private void tblDoctorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDoctorsMouseClicked
        // TODO add your handling code here:
        
        btnBookAppointment.setVisible(true);
        int index = tblDoctors.getSelectedRow();
        TableModel model = tblDoctors.getModel();
        
        doctorFname = model.getValueAt(index, 0).toString();
        
        ArrayList<Encounter> encounterList = encounterHistory.searchEncounter(doctorFname, patient.getUserID());
        populateEncounters(encounterList);
        
        
 
    }//GEN-LAST:event_tblDoctorsMouseClicked

    private void btnSearchDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDoctorActionPerformed
        // TODO add your handling code here:
        String doctorName = txtSearchDoctor.getText();
        
        ArrayList<Doctor> doctorList = doctorDirectory.getDoctorList(doctorName);
        
        if(doctorList.isEmpty()){
            JOptionPane.showMessageDialog(this, "No Results Found!");

        }else{
            
            populateSearchResults(doctorList);
        
        }

    }//GEN-LAST:event_btnSearchDoctorActionPerformed

    private void tblEncountersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEncountersMouseClicked
        // TODO add your handling code here:
        int index = tblEncounters.getSelectedRow();
        TableModel model = tblEncounters.getModel();
        
        Date encounterDate =(Date) model.getValueAt(index, 0);
        
        Encounter selectedEncounter = encounterHistory.getEncounter(encounterDate);
        if(selectedEncounter.getComments().equals(" ")){
            vitalsPanel.setVisible(false);
            JOptionPane.showMessageDialog(this, "No Vitals Added\nINFO: "+selectedEncounter.getInfo());
            
        }else{
            vitalsPanel.setVisible(true);
        
            txtSystole.setText(String.valueOf(selectedEncounter.getSystole()));
            txtDiastole.setText(String.valueOf(selectedEncounter.getDiastole()));
            txtPreDiet.setText(String.valueOf(selectedEncounter.getPreDiet()));
            txtPostDiet.setText(String.valueOf(selectedEncounter.getPostDiet()));
            txtHeartRate.setText(String.valueOf(selectedEncounter.getHeartRate()));
            txtComments.setText(selectedEncounter.getComments());
        }
        
    }//GEN-LAST:event_tblEncountersMouseClicked

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        
        Date appointmentdate = chDate.getDate();
        String info = txtInfo.getText();

        Encounter newEncounter = encounterHistory.addEncounter();
        newEncounter.setEncounterDate(appointmentdate);
        newEncounter.setInfo(info);
        newEncounter.setUserID(patient.getUserID());
        newEncounter.setDoctorName(doctorFname);
        newEncounter.setComments(" ");
        
        JOptionPane.showMessageDialog(this, "New Appointment created with "+doctorFname+" on "+appointmentdate);
        
        tblDoctorsMouseClicked(null);
        
        bookAppointmentPanel.setVisible(false);
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginJPanel login = new LoginJPanel(personDirectory,patientDirectory,doctorDirectory,encounterHistory,hospitalDirectory, houseDirectory, communityDirectory, cityDirectory, splitPane);
        splitPane.setRightComponent(login);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookAppointmentPanel;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnBookAppointment;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSearchDoctor;
    private com.toedter.calendar.JDateChooser chDate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblBP;
    private javax.swing.JLabel lblComments;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDiabetes;
    private javax.swing.JLabel lblDiastole;
    private javax.swing.JLabel lblHeartRate;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel lblPersonalDetails;
    private javax.swing.JLabel lblPostDiet;
    private javax.swing.JLabel lblPreDiet;
    private javax.swing.JLabel lblSystole;
    private javax.swing.JScrollPane scrollEncounters;
    private javax.swing.JTable tblDoctors;
    private javax.swing.JTable tblEncounters;
    private javax.swing.JTextArea txtComments;
    private javax.swing.JTextField txtDiastole;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextArea txtInfo;
    private javax.swing.JTextField txtPostDiet;
    private javax.swing.JTextField txtPreDiet;
    private javax.swing.JTextField txtSearchDoctor;
    private javax.swing.JTextField txtSystole;
    private javax.swing.JPanel vitalsPanel;
    // End of variables declaration//GEN-END:variables

    private void populateDoctorTable(){
        
        DefaultTableModel model = (DefaultTableModel) tblDoctors.getModel();
        model.setRowCount(0);
        
        for(Doctor doctor: doctorDirectory.getDoctorDirectory()){
            if(patient.getCommunity().equals(doctor.getCommunity())){
                Object[] Row =new Object[3];
                Row[0] = doctor.getFirstName();
                Row[1] = doctor.getHospital();
                Row[2] = doctor.getCommunity();

                model.addRow(Row);
            }
            
        }
    }
    
    private void populateSearchResults(ArrayList<Doctor> doctorList){
        DefaultTableModel model = (DefaultTableModel) tblDoctors.getModel();
        model.setRowCount(0);
        
        for(Doctor doctor: doctorList){
            
            Object[] Row =new Object[3];
            Row[0] = doctor.getFirstName();
            Row[1] = doctor.getHospital();
            Row[2] = doctor.getCommunity();
            
            model.addRow(Row);
            
        }
    }
    
    private void populateEncounters(ArrayList<Encounter> encounterList){
        scrollEncounters.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) tblEncounters.getModel();
        model.setRowCount(0);
        
        for(Encounter encounter: encounterList){
            
            Object[] Row =new Object[3];
            Row[0] = encounter.getEncounterDate();
            
            model.addRow(Row);
            
        }
    }

}
