/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import model.Doctor;
import model.DoctorDirectory;
import model.EncounterHistory;
import model.HospitalDirectory;
import model.Patient;
import model.Person;
import model.PersonDirectory;
import model.PatientDirectory;

/**
 *
 * @author mahith
 */
public class SignUpJFrame extends javax.swing.JPanel {

    /**
     * Creates new form SignUpJFrame
     */
    PersonDirectory personDirectory;
    PatientDirectory patientDirectory;
    DoctorDirectory doctorDirectory;
    HospitalDirectory hospitalDirectory;
    Person person;
    EncounterHistory encounterHistory;
    JSplitPane splitPane;
    
    String hospital;
    String specialization;
    int height;
    int weight;
    int age;
    
    
    public SignUpJFrame(Person person,PersonDirectory personDirectory,PatientDirectory patientDirectory, DoctorDirectory doctorDirectory, EncounterHistory encounterHistory,HospitalDirectory hospitalDirectory,JSplitPane splitPane) {
        initComponents();
        
        this.splitPane = splitPane;
        this.personDirectory = personDirectory;
        this.patientDirectory = patientDirectory;
        this.doctorDirectory = doctorDirectory;
        this.encounterHistory = encounterHistory;
        this.hospitalDirectory = hospitalDirectory;
        this.person = person;
        
        btnSignIn.setVisible(false);
        doctorJPanel.setVisible(false);
        patientJPanel.setVisible(false);
        
        if(person==null){
            btnSignIn.setVisible(true);
            btnBack.setVisible(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateAccount = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblRole = new javax.swing.JLabel();
        chRole = new javax.swing.JComboBox<>();
        lblUserID = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        fldPassword = new javax.swing.JPasswordField();
        fldRetype = new javax.swing.JPasswordField();
        lblRetype = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblMobile = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        chDateOfBirth = new com.toedter.calendar.JDateChooser();
        lblDateOfBirth = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        lblGender = new javax.swing.JLabel();
        rdMale = new javax.swing.JRadioButton();
        rdFemale = new javax.swing.JRadioButton();
        doctorJPanel = new javax.swing.JPanel();
        lblHospital = new javax.swing.JLabel();
        txtHospital = new javax.swing.JTextField();
        lblSpecialization = new javax.swing.JLabel();
        txtSpecialization = new javax.swing.JTextField();
        patientJPanel = new javax.swing.JPanel();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblWeight = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        lblHeight = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        btnSignIn = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtCommunity = new javax.swing.JTextField();
        lblCommunity = new javax.swing.JLabel();

        lblCreateAccount.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        lblCreateAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateAccount.setText("Create Account");

        lblFirstName.setText("First Name*");

        txtFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFirstNameFocusLost(evt);
            }
        });
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        lblLastName.setText("Last Name*");

        lblRole.setText("Role*");

        chRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Doctor", "Patient" }));
        chRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chRoleActionPerformed(evt);
            }
        });

        lblUserID.setText("User ID*");

        lblPassword.setText("Password*");

        fldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fldPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fldPasswordFocusLost(evt);
            }
        });

        fldRetype.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fldRetypeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fldRetypeFocusLost(evt);
            }
        });

        lblRetype.setText("Re-type Password*");

        lblEmail.setText("Email*");

        lblMobile.setText("Mobile");

        chDateOfBirth.setMaxSelectableDate(new java.util.Date(1672552868000L));
        chDateOfBirth.setMinSelectableDate(new java.util.Date(-62135747932000L));

        lblDateOfBirth.setText("Date of Birth*");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        lblGender.setText("Gender*");

        rdMale.setText("Male");

        rdFemale.setText("Female");

        lblHospital.setText("Hospital*");

        lblSpecialization.setText("Specialization*");

        javax.swing.GroupLayout doctorJPanelLayout = new javax.swing.GroupLayout(doctorJPanel);
        doctorJPanel.setLayout(doctorJPanelLayout);
        doctorJPanelLayout.setHorizontalGroup(
            doctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHospital)
                .addGap(56, 56, 56)
                .addComponent(txtHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(lblSpecialization)
                .addGap(48, 48, 48)
                .addComponent(txtSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        doctorJPanelLayout.setVerticalGroup(
            doctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorJPanelLayout.createSequentialGroup()
                .addGroup(doctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHospital)
                    .addComponent(txtHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSpecialization))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(doctorJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblAge.setText("Age*");

        lblWeight.setText("Weight*");

        lblHeight.setText("Height*");

        javax.swing.GroupLayout patientJPanelLayout = new javax.swing.GroupLayout(patientJPanel);
        patientJPanel.setLayout(patientJPanelLayout);
        patientJPanelLayout.setHorizontalGroup(
            patientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientJPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(patientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAge)
                    .addComponent(lblWeight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(patientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWeight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(lblHeight)
                .addGap(85, 85, 85)
                .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        patientJPanelLayout.setVerticalGroup(
            patientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeight)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge))
                .addGap(28, 28, 28)
                .addGroup(patientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWeight)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSignIn.setText("Sign in");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblCommunity.setText("Community*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCreateAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFirstName)
                                    .addComponent(lblRole)
                                    .addComponent(lblPassword)
                                    .addComponent(lblEmail)
                                    .addComponent(lblDateOfBirth))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(chDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(txtFirstName)
                                    .addComponent(chRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fldPassword)
                                    .addComponent(txtEmail))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblLastName)
                                            .addComponent(lblUserID))
                                        .addGap(59, 59, 59))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblRetype)
                                            .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLastName)
                                    .addComponent(txtUserID)
                                    .addComponent(fldRetype, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(txtMobile)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdMale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rdFemale))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSignIn)))
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(doctorJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblCommunity)
                        .addGap(41, 41, 41)
                        .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(patientJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnCreate)
                            .addGap(317, 317, 317)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUserID)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCreateAccount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSignIn)
                            .addComponent(btnBack))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstName)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastName)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRole)
                            .addComponent(chRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(fldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRetype)
                    .addComponent(fldRetype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMobile)
                        .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdFemale)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdMale)
                        .addComponent(lblGender))
                    .addComponent(lblDateOfBirth))
                .addGap(18, 18, 18)
                .addComponent(doctorJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommunity)
                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnCreate)
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        String fName = txtFirstName.getText();
        String lName = txtLastName.getText();
        String mobiNum = txtMobile.getText();
        String emailId = txtEmail.getText();
        String role = chRole.getSelectedItem().toString();
        
        Date dateOfBirth = chDateOfBirth.getDate();
        //String gender = JRadioButton1
        String userID = txtUserID.getText();
        String password = new String(fldPassword.getPassword());
        String reType = new String(fldRetype.getPassword());
        String community = txtCommunity.getText();
        
        if(fName.isBlank() || lName.isBlank() || mobiNum.isBlank() || emailId.isBlank() || dateOfBirth.equals("")|| userID.isBlank() || password.isBlank() || community.isBlank()){
            JOptionPane.showMessageDialog(this, "Please enter Mandatory Fields");
        }else if(!emailId.contains("@") || !emailId.contains(".com")){
            JOptionPane.showMessageDialog(this, "Please enter valid Email address");
        }else if(mobiNum.length()!=10){
             JOptionPane.showMessageDialog(this, "Please enter valid Mobile number");
        }
           
        else{
            
        if(role.equals("Patient")){
            try{
                
            height =Integer.parseInt(txtHeight.getText());
            weight = Integer.parseInt(txtWeight.getText());
            age = Integer.parseInt(txtAge.getText());
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Please enter Correct values in Age, height, Weight");
            }
        }
        
        
            if(password.equals(reType)){
                
                if(personDirectory.checkDuplicatePerson(userID)){
                    Person newPerson = personDirectory.addPerson();
                    newPerson.setUserID(userID);
                    newPerson.setFirstName(fName);
                    newPerson.setLastName(lName);
                    newPerson.setPassword(password);
                    newPerson.setRole(role);
                    newPerson.setDateOfBirth(dateOfBirth);
                    newPerson.setMobileNum(mobiNum);
                    newPerson.setEmailAddress(emailId);
                    newPerson.setCommunity(community);
                    
                    if(role=="Patient"){
                    Patient newPatient = patientDirectory.addPatient();

                    newPatient.setFirstName(fName);
                    newPatient.setLastName(lName);
                    newPatient.setUserID(userID);
                    newPatient.setPassword(password);
                    newPatient.setRole(role);
                    newPatient.setDateOfBirth(dateOfBirth);
                    newPatient.setMobileNum(mobiNum);
                    newPatient.setEmailAddress(emailId);
                    newPatient.setHeight(height);
                    newPatient.setWeight(weight);
                    newPatient.setAge(age);
                    newPatient.setCommunity(community);

                }else if(role.equals("Doctor")){
                    
                    hospital = txtHospital.getText();
                    specialization = txtSpecialization.getText();  
                    
                    Doctor newDoctor = doctorDirectory.addDoctor();

                    newDoctor.setFirstName(fName);
                    newDoctor.setLastName(lName);
                    newDoctor.setUserID(userID);
                    newDoctor.setPassword(password);
                    newDoctor.setRole(role);
                    newDoctor.setEmailAddress(emailId);
                    newDoctor.setSpecialization(specialization);
                    newDoctor.setHospital(hospital);
                    newDoctor.setCommunity(community);

                }
                     JOptionPane.showMessageDialog(this, "Signup Successful!");
                     
                     txtFirstName.setText("");
                     txtLastName.setText("");
                     txtEmail.setText("");
                     txtMobile.setText("");
                     chDateOfBirth.setDate(new Date());
                     chRole.setSelectedIndex(0);
                     txtCommunity.setText("");
                     fldPassword.setText("");
                     fldRetype.setText("");
                     
                     if(role.equals("Patient")){
                         txtAge.setText("");
                         txtHeight.setText("");
                         txtWeight.setText("");
                     }else if(role.equals("Doctor")){
                         txtHospital.setText("");
                         txtSpecialization.setText("");
                     }
                }else{
                    JOptionPane.showMessageDialog(this, "User with this ID already exist. Please try again!");
                }

        }else{
            
                JOptionPane.showMessageDialog(this, "Passwords didn't match");
            }
        }
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void chRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chRoleActionPerformed
        // TODO add your handling code here:
        if(!txtFirstName.getText().isBlank() && (chRole.getSelectedItem().toString().equals("Doctor") || chRole.getSelectedItem().equals("Patient"))){
            txtUserID.setText(txtFirstName.getText()+"@"+chRole.getSelectedItem().toString().toLowerCase());
        }else{
            txtUserID.setText("");
        }
        
        if(chRole.getSelectedItem().toString().equals("Patient")){
            doctorJPanel.setVisible(false);
            patientJPanel.setVisible(true);
        }else if(chRole.getSelectedItem().toString().equals("Doctor")){
            patientJPanel.setVisible(false);
            doctorJPanel.setVisible(true);
        }else{
            patientJPanel.setVisible(false);
            doctorJPanel.setVisible(false);
        }
        
        
    }//GEN-LAST:event_chRoleActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
        if(!txtFirstName.getText().isBlank() && (chRole.getSelectedItem().toString().equals("Doctor") || chRole.getSelectedItem().equals("Patient"))){
            txtUserID.setText(txtFirstName.getText()+"@"+chRole.getSelectedItem().toString().toLowerCase());
        }else{
            txtUserID.setText("");
        }
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void fldPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fldPasswordFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fldPasswordFocusGained

    private void fldPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fldPasswordFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_fldPasswordFocusLost

    private void fldRetypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fldRetypeFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fldRetypeFocusGained

    private void fldRetypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fldRetypeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fldRetypeFocusLost

    private void txtFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstNameFocusLost
        // TODO add your handling code here:
        if(!txtFirstName.getText().isBlank() && (chRole.getSelectedItem().toString().equals("Doctor") || chRole.getSelectedItem().equals("Patient"))){
            txtUserID.setText(txtFirstName.getText()+"@"+chRole.getSelectedItem().toString().toLowerCase());
        }else{
            txtUserID.setText("");
        }
    }//GEN-LAST:event_txtFirstNameFocusLost

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
        LoginJPanel login = new LoginJPanel(personDirectory,patientDirectory,doctorDirectory,encounterHistory,hospitalDirectory,splitPane);
        splitPane.setRightComponent(login);
    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //String patientName = txtFirstName.getText();
        if(person.getRole()=="Patient"){
            PatientJPanel patientPane = new PatientJPanel(person, personDirectory, patientDirectory, doctorDirectory,encounterHistory, hospitalDirectory, splitPane);
            splitPane.setRightComponent(patientPane);
        }else if(person.getRole()=="Doctor"){
            DoctorJPanel doc = new DoctorJPanel(person,personDirectory,patientDirectory,doctorDirectory,encounterHistory,hospitalDirectory, splitPane);
            splitPane.setRightComponent(doc);
        }else if(person.getRole()=="System Admin"){
            SystemAdminPanel admin = new SystemAdminPanel(person,personDirectory,patientDirectory,doctorDirectory,encounterHistory,hospitalDirectory,splitPane);
            splitPane.setRightComponent(admin);
        }
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnSignIn;
    private com.toedter.calendar.JDateChooser chDateOfBirth;
    private javax.swing.JComboBox<String> chRole;
    private javax.swing.JPanel doctorJPanel;
    private javax.swing.JPasswordField fldPassword;
    private javax.swing.JPasswordField fldRetype;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblCreateAccount;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblHospital;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRetype;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSpecialization;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JPanel patientJPanel;
    private javax.swing.JRadioButton rdFemale;
    private javax.swing.JRadioButton rdMale;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtHospital;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtSpecialization;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables

    private void saveData(){
        
    }

}
